# Fabric benchmark notebook: 02_polars_vcore_advisor
# Kernel: jupyter
# NOTE: generated by deploy_benchmark_notebooks.py -- edit there, not here.

# %%
# --- Shared benchmark configuration (auto-injected) ---
DATA_WS   = "f1e17fe0-3706-425e-ae65-9fda78946327"
ENG_WS    = "6dc1aae2-1e5d-4ebb-82b9-faf1a63ed5d8"
LH = {
    "source": "e219f8d3-f681-4a46-8cd0-855ab2b9e650",
    "bronze": "52711a64-ef06-4608-b3b4-1330984d3c98",
    "silver": "b7280cc4-8842-443b-b9f3-2d643ff07cf3",
    "gold":   "42643c02-ba40-4f37-ba7c-4ca0d68a3e4a",
}
RESULTS_LH  = "44150c61-a3db-4e45-9b2b-4bdfc58a00b3"
CAPACITY_ID = "ad343e36-f335-4ba3-b261-b739f7e950b0"
ONELAKE     = "onelake.dfs.fabric.microsoft.com"

# PySpark needs a coordinator driver that Polars has no equivalent for. It is
# pinned to the smallest node in deploy_environments.py and counted in CU so the
# overhead is visible (it handicaps Spark, never Polars). Polars = 0 extra.
SPARK_DRIVER_CORES = 4

def abfss(ws, item, sub):
    return f"abfss://{ws}@{ONELAKE}/{item}/{sub}"

def tbl(layer, schema, table):
    """abfss path to a Delta table in one of the data-workspace lakehouses."""
    return abfss(DATA_WS, LH[layer], f"Tables/{schema}/{table}")

def results_dir():
    return abfss(ENG_WS, RESULTS_LH, "Files/bench_results")

def onelake_opts():
    """delta-rs / object_store options for cross-workspace OneLake writes."""
    import notebookutils
    return {"bearer_token": notebookutils.credentials.getToken("storage"),
            "use_fabric_endpoint": "true"}

def _looks_streaming_unsupported(err):
    """True when Polars ran the plan on the in-memory STANDARD engine because the
    streaming engine can't execute some node (e.g. window / rank over-expressions).
    The tell-tale is the sink error 'not yet supported in standard engine. Use
    collect().write_parquet()'. Used ONLY to gate the small-output streaming
    collect() fallback (gold), so a genuine write error is never mistaken for an
    unsupported plan."""
    m = repr(err).lower()
    return ("standard engine" in m
            or "collect().write_parquet" in m
            or ("not supported" in m and "stream" in m)
            or ("not yet supported" in m and "stream" in m))


def scan_delta_stream(path):
    """Return a STREAMING LazyFrame over a Delta table's ACTIVE data files.

    Reading the Delta log's active file list and scanning those Parquet files
    keeps the source streaming while avoiding stale files left by earlier
    overwrites. A *.parquet glob could double-count those inactive files."""
    import polars as pl
    from deltalake import DeltaTable
    files = [f[7:] if f.startswith("file://") else f
             for f in DeltaTable(path).file_uris()]
    return pl.scan_parquet(files)


def _is_disk_full(err):
    """True when a write failed because the target filesystem ran out of space."""
    import errno
    if isinstance(err, OSError) and err.errno == errno.ENOSPC:
        return True
    m = repr(err).lower()
    return "no space left" in m or "enospc" in m or "disk quota" in m


def _spill_bases():
    """Ordered candidate directories for the streaming spill, FAST LOCAL DISK
    FIRST. `/tmp` is node-local NVMe; the `/lakehouse/default/Files` mount is
    OneLake-backed (network FUSE), so writing the spill there costs a full extra
    network round-trip (write it out, then read it back for the Delta load) and
    is ~10-20x slower. We therefore spill locally whenever the output fits, and
    fall back to the big network mount only for outputs too large for the node's
    local disk (e.g. the ~38GB 50gb fact, which does not fit in /tmp)."""
    import os, shutil
    order = []
    for c in ("/tmp", "/lakehouse/default/Files"):
        try:
            free = shutil.disk_usage(c).free
        except Exception:
            continue
        order.append((c, free))
    if not order:
        order = [("/tmp", 0)]
    return [os.path.join(c, "_polars_sink_tmp") for c, _ in order]


def _write_delta_from_dir(pdir, target):
    """Load a directory of Parquet row groups into Delta INCREMENTALLY via a
    pyarrow dataset (write_deltalake scans batch-by-batch, so it never holds the
    whole table in RAM). One fresh-token retry covers a transient OneLake blip."""
    import time as _time
    import pyarrow.dataset as pads
    from deltalake import write_deltalake
    ds = pads.dataset(pdir, format="parquet")
    for attempt in range(2):
        try:
            write_deltalake(target, ds, mode="overwrite",
                            schema_mode="overwrite",
                            storage_options=onelake_opts())
            return
        except Exception as e:
            if attempt == 0:
                print(f"  write_deltalake failed ({e!r}); retry with fresh token")
                _time.sleep(3)
            else:
                raise


def polars_sink_delta(lf, target, allow_collect_fallback=False):
    """Write a Polars LazyFrame to a Delta table WITHOUT ever materializing the
    full frame in RAM. Peak memory is O(batch), not O(table) -- a headless ETL
    never needs the whole result in memory.

    The benchmark notebooks pin a modern Polars release with native
    `LazyFrame.sink_delta`, so the normal path streams directly to Delta. The
    Parquet spill path remains as a compatibility fallback for older runtimes.

    The spill goes to FAST NODE-LOCAL DISK (/tmp) whenever the output fits there;
    only outputs too large for local disk fall back to the big OneLake-backed
    mount (see _spill_bases). Spilling to the network mount works but is ~10-20x
    slower, so we avoid it unless the local node disk can't hold the output.

    allow_collect_fallback (gold ONLY): if the streaming engine genuinely can't
    run the plan (some window / rank over-expressions), collect() the result with
    the in-memory engine and write that. Safe ONLY because gold output is small,
    aggregated data. Bronze and silver leave this False and FAIL LOUDLY instead --
    silently materializing their full-size output is exactly the OOM (SIGKILL -9)
    we are avoiding.

    Returns the row count from Delta's transaction-log metadata (no data re-scan),
    or None if it can't be read cheaply."""
    import os, shutil, uuid
    import polars as pl
    if hasattr(pl.LazyFrame, "sink_delta"):
        # Pinned benchmark runtime: native streaming Delta sink.
        lf.sink_delta(
            target,
            mode="overwrite",
            storage_options=onelake_opts(),
            delta_write_options={"schema_mode": "overwrite"},
        )
    else:
        bases = _spill_bases()
        last = len(bases) - 1
        disk_err = None
        for i, base in enumerate(bases):
            pdir = os.path.join(base, uuid.uuid4().hex)
            os.makedirs(pdir, exist_ok=True)
            pfile = os.path.join(pdir, "data.parquet")
            try:
                try:
                    # maintain_order=False lets the STREAMING engine run
                    # order-insensitive plans (joins, dedupe). With the default
                    # maintain_order=True Polars 1.6 falls back to the standard
                    # (in-memory) engine for such plans -- which cannot sink and
                    # would otherwise force a full-frame collect() (the OOM path).
                    lf.sink_parquet(pfile, maintain_order=False)
                except Exception as e:
                    if allow_collect_fallback and _looks_streaming_unsupported(e):
                        # gold window/rank: the streaming engine can't fuse the
                        # over()/rank() into the sink, so collect WITH THE
                        # STREAMING ENGINE -- it streams the group_by (bounded)
                        # and only materializes the small aggregated result, then
                        # runs the window on that. Safe because gold output is
                        # tiny; bronze/silver never set this (their result is
                        # full-size, so any collect would be the OOM we avoid).
                        print(f"  streaming sink can't fuse this plan ({e!r}); "
                              f"streaming collect() of the small aggregated output")
                        lf.collect(engine="streaming").write_parquet(pfile)
                    elif _is_disk_full(e) and i < last:
                        # Local spill dir is too small for this output -- fall back
                        # to the next (larger, network-backed) mount.
                        print(f"  spill dir {base} out of space ({e!r}); "
                              f"falling back to {bases[i + 1]}")
                        disk_err = e
                        continue
                    else:
                        raise
                _write_delta_from_dir(pdir, target)
                break
            finally:
                shutil.rmtree(pdir, ignore_errors=True)
        else:
            raise disk_err or RuntimeError("no usable spill location for sink_parquet")
    try:
        from deltalake import DeltaTable
        add = DeltaTable(target, storage_options=onelake_opts()).get_add_actions(flatten=True)
        vals = add.column("num_records").to_pylist()
        return int(sum(v for v in vals if v is not None))
    except Exception:
        return None

# TPC-DS subset used by the benchmark (one big fact + a realistic star of dims)
FACT = "store_sales"
DIMS = ["date_dim", "item", "store", "customer", "customer_address",
        "customer_demographics", "household_demographics", "promotion"]
SIZES = ["1gb", "10gb", "50gb"]

# %%
# --- Metrics harness (auto-injected): wall-clock + peak memory + OOM + CU ctx ---
import time, json, threading, datetime, os, uuid
try:
    import psutil
except Exception:
    psutil = None

def _uid():
    return datetime.datetime.utcnow().strftime("%Y%m%d%H%M%S") + "-" + uuid.uuid4().hex[:6]

RUN_ID = _uid()
print("RUN_ID =", RUN_ID)

class _PeakMem:
    """Samples process (+child) RSS in a background thread to find the peak.

    On Spark this only sees the driver; executor pressure shows up in CU and
    the Spark UI, which is why we also record capacity + time window below."""
    def __init__(self):
        self.peak = 0; self._run = False; self._t = None
    def _loop(self):
        p = psutil.Process(os.getpid()) if psutil else None
        while self._run and p is not None:
            try:
                rss = p.memory_info().rss
                for c in p.children(recursive=True):
                    try: rss += c.memory_info().rss
                    except Exception: pass
                self.peak = max(self.peak, rss)
            except Exception:
                pass
            time.sleep(0.25)
    def __enter__(self):
        if psutil is not None:
            self._run = True
            self._t = threading.Thread(target=self._loop, daemon=True); self._t.start()
        return self
    def __exit__(self, *a):
        self._run = False
        if self._t is not None:
            self._t.join(timeout=1)

def _write_result(row):
    """Append one JSON result file to lh_bench_results/Files/bench_results.
    JSON files avoid cross-engine Delta schema conflicts."""
    import notebookutils
    result_dir = results_dir()
    notebookutils.fs.mkdirs(result_dir)
    fn = f"{row['run_id']}_{row['engine']}_{row['size']}_{row['layer']}_{row['stage']}.json"
    fn = fn.replace(":", "-").replace("/", "-")
    notebookutils.fs.put(f"{result_dir}/{fn}", json.dumps(row, default=str), True)

def run_stage(engine, size, layer, stage, fn, vcores=None):
    """Time `fn`, capture peak memory + status (success/failed/oom), persist a
    result row, and return the status string. Never raises."""
    try:
        from polars.exceptions import PanicException
        panic_types = (PanicException,)
    except ImportError:
        panic_types = ()
    start = datetime.datetime.utcnow()
    t0 = time.perf_counter(); status = "success"; err = None; rows = None
    with _PeakMem() as pm:
        try:
            rows = fn()
        except MemoryError as e:
            status, err = "oom", repr(e)
        except panic_types as e:
            status, err = "failed", repr(e)
        except Exception as e:
            m = repr(e).lower()
            status = "oom" if ("outofmemory" in m or "out of memory" in m
                               or "memoryerror" in m or "oom" in m) else "failed"
            err = repr(e)
    wall = time.perf_counter() - t0
    end = datetime.datetime.utcnow()
    # CU-seconds (Fabric: cores * 0.5 * active_seconds; startup not billed).
    # Spark counts driver + worker cores; Polars is single-node (no driver).
    driver_cores = SPARK_DRIVER_CORES if engine == "pyspark" else 0
    total_cores = (vcores + driver_cores) if vcores else None
    cu_seconds = round(total_cores * 0.5 * wall, 3) if total_cores else None
    row = {
        "run_id": RUN_ID, "engine": engine, "size": size, "layer": layer,
        "stage": stage, "status": status, "wall_seconds": round(wall, 3),
        "peak_mem_mb": round(pm.peak / 1e6, 1) if pm.peak else None,
        "rows": int(rows) if rows is not None else None,
        "error": (str(err)[:900] if err else None),
        "capacity_id": CAPACITY_ID, "vcores": vcores,
        "driver_cores": driver_cores, "total_cores": total_cores,
        "cu_seconds": cu_seconds,
        "start_utc": start.isoformat(), "end_utc": end.isoformat(),
        "recorded_utc": datetime.datetime.utcnow().isoformat(),
    }
    try:
        _write_result(row)
    except Exception as e:
        print("WARN: could not persist result:", repr(e))
    tag = "OK " if status == "success" else status.upper()
    print(f"[{tag}] {stage}: {wall:.2f}s  peak={row['peak_mem_mb']}MB  "
          f"rows={row['rows']}  cu_s={cu_seconds}")
    if err:
        print("      ->", str(err)[:300])
    return status

# %% [markdown]
# # 02 - Polars vCore advisor
# Given a `size` and `layer`, measures the **actual on-disk (ZSTD Parquet) size of that layer's input** in OneLake, then applies a **streaming memory model** (Polars lazy + `collect(streaming=True)`): peak memory is driven by the largest blocking op on the **column-pruned** dominant input, not the sum of all inputs. Recommends a vCore count from the 4/8/16/32/64 ladder (8 GB RAM per vCore).
# 
# If the true upstream hasn't been produced yet for a size, it falls back to a **source proxy** (silver->source, gold->source `store_sales`) so you can right-size *before* the first run, with a printed caveat.
# 
# The recommendation applies to **both engines**: set the same worker vCores for Polars (`CONFIGURE_VCORES`) and PySpark (`deploy_environments.py`) to keep the comparison like-for-like. It **reads no full dataset into memory** -- it only lists file sizes.

# %%
# Parameters
size  = "10gb"    # one of: 1gb, 10gb, 50gb
layer = "silver"  # one of: bronze, silver, gold

# %%
import notebookutils

# ---- Streaming memory model (Polars lazy + collect(streaming=True)) -----------
# A streaming pipeline's peak memory is driven by the largest BLOCKING operation
# on the PRUNED working set (dedupe hash / join build / aggregation table), NOT by
# the sum of all inputs x a big factor. Projection pushdown means unused columns
# are never loaded, so we size from the dominant, column-pruned input. Constants
# are tunable -- refine them against real peak_mem_mb in bench.results.
DECOMPRESS  = 5.0    # ZSTD Parquet on disk -> Arrow in-memory
HEADROOM    = 1.3    # safety margin on the working set
BASELINE_GB = 3.0    # interpreter + Arrow/Polars fixed overhead
VCORE_GB    = 8.0    # Fabric Python kernel: 8 GB RAM per vCore
LADDER      = [4, 8, 16, 32, 64]

# Column-count ratios model projection pushdown (Parquet is columnar => ~linear).
SS_TOTAL_COLS  = 23   # store_sales columns
SILVER_SS_COLS = 8    # columns silver actually reads from store_sales
SC_TOTAL_COLS  = 22   # sales_conformed columns
GOLD_MART_COLS = 6    # widest single gold mart's column set

schema = f"polars_{size}"
LAYER = {
    "bronze": {"primary": ("source", f"Files/tpcds/{size}"),
               "tables": [FACT] + DIMS, "driver": "largest",
               "prune": {}, "op_factor": 1.5,
               "note": "streamed scan->write, one table at a time"},
    "silver": {"primary": ("bronze", f"Tables/{schema}"),
               "fallback": ("source", f"Files/tpcds/{size}"),  # bronze ~= source passthrough
               "tables": [FACT, "date_dim", "item", "store", "customer",
                          "customer_address"], "driver": "sum",
               "prune": {FACT: SILVER_SS_COLS / SS_TOTAL_COLS}, "op_factor": 2.5,
               "note": f"5 joins + dedupe; fact pruned to {SILVER_SS_COLS}/{SS_TOTAL_COLS} cols"},
    "gold":   {"primary": ("silver", f"Tables/{schema}"),
               "tables": ["sales_conformed"], "driver": "sum",
               "prune": {"sales_conformed": GOLD_MART_COLS / SC_TOTAL_COLS}, "op_factor": 1.5,
               "note": f"group-by/window reads ~{GOLD_MART_COLS}/{SC_TOTAL_COLS} cols (spillable)"},
}
if layer not in LAYER:
    raise ValueError(f"layer must be one of {list(LAYER)}; got {layer!r}")
spec = LAYER[layer]

def parquet_bytes(path):
    total = 0
    try:
        entries = notebookutils.fs.ls(path)
    except Exception:
        return 0
    for it in entries:
        is_dir = getattr(it, "isDir", None)
        if is_dir is None:
            is_dir = (it.size == 0 and not it.name.endswith(".parquet"))
        if is_dir:
            total += parquet_bytes(it.path)
        elif it.name.endswith(".parquet"):
            total += it.size
    return total

def measure(lh_key, base, tables):
    uri = abfss(DATA_WS, LH[lh_key], base)
    return uri, {t: parquet_bytes(f"{uri}/{t}") for t in tables}

# Measure the true upstream; fall back to a proxy if it hasn't been produced yet
# so the advisor is usable BEFORE a fresh size has been run end-to-end.
lh_key, base = spec["primary"]
uri, sizes = measure(lh_key, base, spec["tables"])
proxy = None
if sum(sizes.values()) == 0 and spec.get("fallback"):
    lh_key, base = spec["fallback"]
    uri, sizes = measure(lh_key, base, spec["tables"])
    proxy = "source (bronze not produced yet; bronze ~= source passthrough)"
if sum(sizes.values()) == 0 and layer == "gold":
    uri, ss = measure("source", f"Files/tpcds/{size}", [FACT])
    sizes = {"sales_conformed": ss[FACT]}   # ~same rows/width as the conformed fact
    proxy = "source store_sales (silver not produced yet; conformed ~= fact)"
if sum(sizes.values()) == 0:
    raise RuntimeError(
        f"No Parquet found for layer={layer} size={size}. Generate the upstream "
        f"first (bronze<-init_pipeline; silver<-bronze; gold<-silver).")

print(f"measuring {layer} input under {uri}" + (f"  [proxy: {proxy}]" if proxy else ""))
pruned = {}
for t, b in sizes.items():
    pr = spec["prune"].get(t, 1.0)
    pruned[t] = b * pr
    tag = f"  (x{pr:.2f} projection prune)" if pr != 1.0 else ""
    print(f"  {t:20s} {b/1e9:8.3f} GB -> {pruned[t]/1e9:7.3f} GB effective{tag}")

dom = sum(pruned.values()) if spec["driver"] == "sum" else max(pruned.values() or [0])
decompressed = dom / 1e9 * DECOMPRESS
working_set  = decompressed * spec["op_factor"]
required_gb  = working_set * HEADROOM + BASELINE_GB
rec = next((v for v in LADDER if v * VCORE_GB >= required_gb), LADDER[-1])
capped = required_gb > LADDER[-1] * VCORE_GB

bar = "=" * 70
print("\n" + bar)
print(f"Polars vCore recommendation (streaming model)  |  size={size} layer={layer}")
print(bar)
print(f"  dominant input ({spec['driver']}, pruned): {dom/1e9:8.3f} GB on disk")
print(f"  x decompress {DECOMPRESS} -> {decompressed:.1f} GB in memory")
print(f"  x op_factor {spec['op_factor']} ({spec['note']}) -> {working_set:.1f} GB working set")
print(f"  x headroom {HEADROOM} + {BASELINE_GB} GB baseline -> required {required_gb:.1f} GB")
print(f"  / {VCORE_GB:.0f} GB per vCore -> need >= {required_gb/VCORE_GB:.1f} vCores")
print("-" * 70)
print(f"  RECOMMENDED vCores: {rec}   ({int(rec*VCORE_GB)} GB RAM)")
if capped:
    print(f"  WARNING: estimate ({required_gb:.0f} GB) exceeds the 64-vCore / "
          f"{int(LADDER[-1]*VCORE_GB)} GB max node -- expect a heavily spill-bound")
    print(f"  run or a legitimate OOM result at {size}/{layer}.")
print(bar)
print("\nFAIRNESS - apply the SAME vCores to BOTH engines (like-for-like):")
print(f"  * Polars : set this layer to {rec} vCores via CONFIGURE_VCORES in")
print(f"             deploy_benchmark_notebooks.py (the %%configure cell).")
print(f"  * PySpark: set the pyspark-{layer} environment to the SAME {rec} worker")
print(f"             vCores (executors x executor-cores) in deploy_environments.py")
print(f"             and re-publish. Spark also runs a fixed 4-core driver, which")
print(f"             is disclosed and counted in CU -- workers stay matched at {rec}.")
print("  Set each layer's budget to the MAX across sizes so both engines share")
print("  one fixed per-layer vCore count (the fairness contract).")

notebookutils.notebook.exit(str(rec))
