# Fabric benchmark notebook: 12_polars_gold
# Kernel: jupyter
# NOTE: generated by deploy_benchmark_notebooks.py -- edit there, not here.

# %%
# --- Shared benchmark configuration (auto-injected) ---
DATA_WS   = "f1e17fe0-3706-425e-ae65-9fda78946327"
ENG_WS    = "6dc1aae2-1e5d-4ebb-82b9-faf1a63ed5d8"
LH = {
    "source": "e219f8d3-f681-4a46-8cd0-855ab2b9e650",
    "bronze": "52711a64-ef06-4608-b3b4-1330984d3c98",
    "silver": "b7280cc4-8842-443b-b9f3-2d643ff07cf3",
    "gold":   "42643c02-ba40-4f37-ba7c-4ca0d68a3e4a",
}
RESULTS_LH  = "44150c61-a3db-4e45-9b2b-4bdfc58a00b3"
CAPACITY_ID = "ad343e36-f335-4ba3-b261-b739f7e950b0"
ONELAKE     = "onelake.dfs.fabric.microsoft.com"

def abfss(ws, item, sub):
    return f"abfss://{ws}@{ONELAKE}/{item}/{sub}"

def tbl(layer, schema, table):
    """abfss path to a Delta table in one of the data-workspace lakehouses."""
    return abfss(DATA_WS, LH[layer], f"Tables/{schema}/{table}")

def results_dir():
    return abfss(ENG_WS, RESULTS_LH, "Files/bench_results")

def onelake_opts():
    """delta-rs / object_store options for cross-workspace OneLake writes."""
    import notebookutils
    return {"bearer_token": notebookutils.credentials.getToken("storage"),
            "use_fabric_endpoint": "true"}

# TPC-DS subset used by the benchmark (one big fact + a realistic star of dims)
FACT = "store_sales"
DIMS = ["date_dim", "item", "store", "customer", "customer_address",
        "customer_demographics", "household_demographics", "promotion"]
SIZES = ["1gb", "10gb", "50gb"]

# %%
# --- Metrics harness (auto-injected): wall-clock + peak memory + OOM + CU ctx ---
import time, json, threading, datetime, os, uuid
try:
    import psutil
except Exception:
    psutil = None

def _uid():
    return datetime.datetime.utcnow().strftime("%Y%m%d%H%M%S") + "-" + uuid.uuid4().hex[:6]

RUN_ID = _uid()
print("RUN_ID =", RUN_ID)

class _PeakMem:
    """Samples process (+child) RSS in a background thread to find the peak.

    On Spark this only sees the driver; executor pressure shows up in CU and
    the Spark UI, which is why we also record capacity + time window below."""
    def __init__(self):
        self.peak = 0; self._run = False; self._t = None
    def _loop(self):
        p = psutil.Process(os.getpid()) if psutil else None
        while self._run and p is not None:
            try:
                rss = p.memory_info().rss
                for c in p.children(recursive=True):
                    try: rss += c.memory_info().rss
                    except Exception: pass
                self.peak = max(self.peak, rss)
            except Exception:
                pass
            time.sleep(0.25)
    def __enter__(self):
        if psutil is not None:
            self._run = True
            self._t = threading.Thread(target=self._loop, daemon=True); self._t.start()
        return self
    def __exit__(self, *a):
        self._run = False
        if self._t is not None:
            self._t.join(timeout=1)

def _write_result(row):
    """Append one JSON result file to lh_bench_results/Files/bench_results.
    JSON files avoid cross-engine Delta schema conflicts."""
    import notebookutils
    fn = f"{row['run_id']}_{row['engine']}_{row['size']}_{row['layer']}_{row['stage']}.json"
    fn = fn.replace(":", "-").replace("/", "-")
    notebookutils.fs.put(f"{results_dir()}/{fn}", json.dumps(row, default=str), True)

def run_stage(engine, size, layer, stage, fn, vcores=None):
    """Time `fn`, capture peak memory + status (success/failed/oom), persist a
    result row, and return the status string. Never raises."""
    start = datetime.datetime.utcnow()
    t0 = time.perf_counter(); status = "success"; err = None; rows = None
    with _PeakMem() as pm:
        try:
            rows = fn()
        except MemoryError as e:
            status, err = "oom", repr(e)
        except Exception as e:
            m = repr(e).lower()
            status = "oom" if ("outofmemory" in m or "out of memory" in m
                               or "memoryerror" in m or "oom" in m) else "failed"
            err = repr(e)
    wall = time.perf_counter() - t0
    end = datetime.datetime.utcnow()
    row = {
        "run_id": RUN_ID, "engine": engine, "size": size, "layer": layer,
        "stage": stage, "status": status, "wall_seconds": round(wall, 3),
        "peak_mem_mb": round(pm.peak / 1e6, 1) if pm.peak else None,
        "rows": int(rows) if rows is not None else None,
        "error": (str(err)[:900] if err else None),
        "capacity_id": CAPACITY_ID, "vcores": vcores,
        "start_utc": start.isoformat(), "end_utc": end.isoformat(),
        "recorded_utc": datetime.datetime.utcnow().isoformat(),
    }
    try:
        _write_result(row)
    except Exception as e:
        print("WARN: could not persist result:", repr(e))
    tag = "OK " if status == "success" else status.upper()
    print(f"[{tag}] {stage}: {wall:.2f}s  peak={row['peak_mem_mb']}MB  rows={row['rows']}")
    if err:
        print("      ->", str(err)[:300])
    return status

# %% [markdown]
# # 12 - Polars Gold (aggregates / windows)
# Reads `silver.sales_conformed` from the **default lakehouse (`lh_bench_silver`)** and builds curated marts (group-bys + window functions), written to `lh_bench_gold`. Curated output is usually much smaller than the scan.
# 
# **Recommended vCores: 16.**

# %%
# Parameters -- change `size` per run; set the notebook's vCores in Settings > Compute.
engine = "polars"
size   = "1gb"          # one of: 1gb, 10gb, 50gb
VCORES = 16             # recorded for context; matches the vCores you set in Settings

# %%
schema_out = f"{engine}_{size}"

# %%
import polars as pl
sc_path = f"/lakehouse/default/Tables/{schema_out}/sales_conformed"  # default = silver

def gold_sales_by_date_store_cat():
    sc = pl.read_delta(sc_path)
    g = (sc.group_by(["d_year", "d_moy", "s_store_sk", "i_category"])
           .agg([pl.col("net_amount").sum().alias("net_revenue"),
                 pl.len().alias("line_items"),
                 pl.col("net_amount").mean().alias("avg_line")]))
    g.write_delta(tbl("gold", schema_out, "sales_by_date_store_cat"),
                  mode="overwrite", storage_options=onelake_opts())
    return g.height

def gold_monthly_store_revenue():
    sc = pl.read_delta(sc_path)
    g = (sc.group_by(["s_store_sk", "d_year", "d_moy"])
           .agg(pl.col("net_amount").sum().alias("revenue"))
           .sort(["s_store_sk", "d_year", "d_moy"])
           .with_columns(pl.col("revenue").cum_sum().over("s_store_sk").alias("running_revenue")))
    g.write_delta(tbl("gold", schema_out, "monthly_store_revenue"),
                  mode="overwrite", storage_options=onelake_opts())
    return g.height

def gold_top_items():
    sc = pl.read_delta(sc_path)
    g = (sc.group_by(["i_category", "i_item_sk"])
           .agg(pl.col("net_amount").sum().alias("revenue"))
           .with_columns(pl.col("revenue").rank("dense", descending=True)
                           .over("i_category").alias("rank_in_cat"))
           .filter(pl.col("rank_in_cat") <= 20))
    g.write_delta(tbl("gold", schema_out, "top_items_per_category"),
                  mode="overwrite", storage_options=onelake_opts())
    return g.height

run_stage(engine, size, "gold", "gold:sales_by_date_store_cat", gold_sales_by_date_store_cat, vcores=VCORES)
run_stage(engine, size, "gold", "gold:monthly_store_revenue",  gold_monthly_store_revenue,  vcores=VCORES)
run_stage(engine, size, "gold", "gold:top_items_per_category",  gold_top_items,              vcores=VCORES)
