# Fabric benchmark notebook: 20_pyspark_bronze
# Kernel: synapse_pyspark
# NOTE: generated by deploy_benchmark_notebooks.py -- edit there, not here.

# %%
# --- Shared benchmark configuration (auto-injected) ---
DATA_WS   = "f1e17fe0-3706-425e-ae65-9fda78946327"
ENG_WS    = "6dc1aae2-1e5d-4ebb-82b9-faf1a63ed5d8"
LH = {
    "source": "e219f8d3-f681-4a46-8cd0-855ab2b9e650",
    "bronze": "52711a64-ef06-4608-b3b4-1330984d3c98",
    "silver": "b7280cc4-8842-443b-b9f3-2d643ff07cf3",
    "gold":   "42643c02-ba40-4f37-ba7c-4ca0d68a3e4a",
}
RESULTS_LH  = "44150c61-a3db-4e45-9b2b-4bdfc58a00b3"
CAPACITY_ID = "ad343e36-f335-4ba3-b261-b739f7e950b0"
ONELAKE     = "onelake.dfs.fabric.microsoft.com"

# PySpark needs a coordinator driver that Polars has no equivalent for. It is
# pinned to the smallest node in deploy_environments.py and counted in CU so the
# overhead is visible (it handicaps Spark, never Polars). Polars = 0 extra.
SPARK_DRIVER_CORES = 4

def abfss(ws, item, sub):
    return f"abfss://{ws}@{ONELAKE}/{item}/{sub}"

def tbl(layer, schema, table):
    """abfss path to a Delta table in one of the data-workspace lakehouses."""
    return abfss(DATA_WS, LH[layer], f"Tables/{schema}/{table}")

def results_dir():
    return abfss(ENG_WS, RESULTS_LH, "Files/bench_results")

def onelake_opts():
    """delta-rs / object_store options for cross-workspace OneLake writes."""
    import notebookutils
    return {"bearer_token": notebookutils.credentials.getToken("storage"),
            "use_fabric_endpoint": "true"}

def _looks_streaming_unsupported(err):
    """True when Polars ran the plan on the in-memory STANDARD engine because the
    streaming engine can't execute some node (e.g. window / rank over-expressions).
    The tell-tale is the sink error 'not yet supported in standard engine. Use
    collect().write_parquet()'. Used ONLY to gate the small-output streaming
    collect() fallback (gold), so a genuine write error is never mistaken for an
    unsupported plan."""
    m = repr(err).lower()
    return ("standard engine" in m
            or "collect().write_parquet" in m
            or ("not supported" in m and "stream" in m)
            or ("not yet supported" in m and "stream" in m))


def scan_delta_stream(path):
    """Return a STREAMING LazyFrame over a Delta table's ACTIVE data files.

    Reading the Delta log's active file list and scanning those Parquet files
    keeps the source streaming while avoiding stale files left by earlier
    overwrites. A *.parquet glob could double-count those inactive files."""
    import polars as pl
    from deltalake import DeltaTable
    files = [f[7:] if f.startswith("file://") else f
             for f in DeltaTable(path).file_uris()]
    return pl.scan_parquet(files)


def _is_disk_full(err):
    """True when a write failed because the target filesystem ran out of space."""
    import errno
    if isinstance(err, OSError) and err.errno == errno.ENOSPC:
        return True
    m = repr(err).lower()
    return "no space left" in m or "enospc" in m or "disk quota" in m


def _spill_bases():
    """Ordered candidate directories for the streaming spill, FAST LOCAL DISK
    FIRST. `/tmp` is node-local NVMe; the `/lakehouse/default/Files` mount is
    OneLake-backed (network FUSE), so writing the spill there costs a full extra
    network round-trip (write it out, then read it back for the Delta load) and
    is ~10-20x slower. We therefore spill locally whenever the output fits, and
    fall back to the big network mount only for outputs too large for the node's
    local disk (e.g. the ~38GB 50gb fact, which does not fit in /tmp)."""
    import os, shutil
    order = []
    for c in ("/tmp", "/lakehouse/default/Files"):
        try:
            free = shutil.disk_usage(c).free
        except Exception:
            continue
        order.append((c, free))
    if not order:
        order = [("/tmp", 0)]
    return [os.path.join(c, "_polars_sink_tmp") for c, _ in order]


def _write_delta_from_dir(pdir, target):
    """Load a directory of Parquet row groups into Delta INCREMENTALLY via a
    pyarrow dataset (write_deltalake scans batch-by-batch, so it never holds the
    whole table in RAM). One fresh-token retry covers a transient OneLake blip."""
    import time as _time
    import pyarrow.dataset as pads
    from deltalake import write_deltalake
    ds = pads.dataset(pdir, format="parquet")
    for attempt in range(2):
        try:
            write_deltalake(target, ds, mode="overwrite",
                            schema_mode="overwrite",
                            storage_options=onelake_opts())
            return
        except Exception as e:
            if attempt == 0:
                print(f"  write_deltalake failed ({e!r}); retry with fresh token")
                _time.sleep(3)
            else:
                raise


def polars_sink_delta(lf, target, allow_collect_fallback=False):
    """Write a Polars LazyFrame to a Delta table WITHOUT ever materializing the
    full frame in RAM. Peak memory is O(batch), not O(table) -- a headless ETL
    never needs the whole result in memory.

    The benchmark notebooks pin a modern Polars release with native
    `LazyFrame.sink_delta`, so the normal path streams directly to Delta. The
    Parquet spill path remains as a compatibility fallback for older runtimes.

    The spill goes to FAST NODE-LOCAL DISK (/tmp) whenever the output fits there;
    only outputs too large for local disk fall back to the big OneLake-backed
    mount (see _spill_bases). Spilling to the network mount works but is ~10-20x
    slower, so we avoid it unless the local node disk can't hold the output.

    allow_collect_fallback (gold ONLY): if the streaming engine genuinely can't
    run the plan (some window / rank over-expressions), collect() the result with
    the in-memory engine and write that. Safe ONLY because gold output is small,
    aggregated data. Bronze and silver leave this False and FAIL LOUDLY instead --
    silently materializing their full-size output is exactly the OOM (SIGKILL -9)
    we are avoiding.

    Returns the row count from Delta's transaction-log metadata (no data re-scan),
    or None if it can't be read cheaply."""
    import os, shutil, uuid
    import polars as pl
    if hasattr(pl.LazyFrame, "sink_delta"):
        # Pinned benchmark runtime: native streaming Delta sink.
        lf.sink_delta(
            target,
            mode="overwrite",
            storage_options=onelake_opts(),
            delta_write_options={"schema_mode": "overwrite"},
        )
    else:
        bases = _spill_bases()
        last = len(bases) - 1
        disk_err = None
        for i, base in enumerate(bases):
            pdir = os.path.join(base, uuid.uuid4().hex)
            os.makedirs(pdir, exist_ok=True)
            pfile = os.path.join(pdir, "data.parquet")
            try:
                try:
                    # maintain_order=False lets the STREAMING engine run
                    # order-insensitive plans (joins, dedupe). With the default
                    # maintain_order=True Polars 1.6 falls back to the standard
                    # (in-memory) engine for such plans -- which cannot sink and
                    # would otherwise force a full-frame collect() (the OOM path).
                    lf.sink_parquet(pfile, maintain_order=False)
                except Exception as e:
                    if allow_collect_fallback and _looks_streaming_unsupported(e):
                        # gold window/rank: the streaming engine can't fuse the
                        # over()/rank() into the sink, so collect WITH THE
                        # STREAMING ENGINE -- it streams the group_by (bounded)
                        # and only materializes the small aggregated result, then
                        # runs the window on that. Safe because gold output is
                        # tiny; bronze/silver never set this (their result is
                        # full-size, so any collect would be the OOM we avoid).
                        print(f"  streaming sink can't fuse this plan ({e!r}); "
                              f"streaming collect() of the small aggregated output")
                        lf.collect(engine="streaming").write_parquet(pfile)
                    elif _is_disk_full(e) and i < last:
                        # Local spill dir is too small for this output -- fall back
                        # to the next (larger, network-backed) mount.
                        print(f"  spill dir {base} out of space ({e!r}); "
                              f"falling back to {bases[i + 1]}")
                        disk_err = e
                        continue
                    else:
                        raise
                _write_delta_from_dir(pdir, target)
                break
            finally:
                shutil.rmtree(pdir, ignore_errors=True)
        else:
            raise disk_err or RuntimeError("no usable spill location for sink_parquet")
    try:
        from deltalake import DeltaTable
        add = DeltaTable(target, storage_options=onelake_opts()).get_add_actions(flatten=True)
        vals = add.column("num_records").to_pylist()
        return int(sum(v for v in vals if v is not None))
    except Exception:
        return None

# TPC-DS subset used by the benchmark (one big fact + a realistic star of dims)
FACT = "store_sales"
DIMS = ["date_dim", "item", "store", "customer", "customer_address",
        "customer_demographics", "household_demographics", "promotion"]
SIZES = ["1gb", "10gb", "50gb"]

# %%
# --- Metrics harness (auto-injected): wall-clock + peak memory + OOM + CU ctx ---
import time, json, threading, datetime, os, uuid
try:
    import psutil
except Exception:
    psutil = None

def _uid():
    return datetime.datetime.utcnow().strftime("%Y%m%d%H%M%S") + "-" + uuid.uuid4().hex[:6]

RUN_ID = _uid()
print("RUN_ID =", RUN_ID)

class _PeakMem:
    """Samples process (+child) RSS in a background thread to find the peak.

    On Spark this only sees the driver; executor pressure shows up in CU and
    the Spark UI, which is why we also record capacity + time window below."""
    def __init__(self):
        self.peak = 0; self._run = False; self._t = None
    def _loop(self):
        p = psutil.Process(os.getpid()) if psutil else None
        while self._run and p is not None:
            try:
                rss = p.memory_info().rss
                for c in p.children(recursive=True):
                    try: rss += c.memory_info().rss
                    except Exception: pass
                self.peak = max(self.peak, rss)
            except Exception:
                pass
            time.sleep(0.25)
    def __enter__(self):
        if psutil is not None:
            self._run = True
            self._t = threading.Thread(target=self._loop, daemon=True); self._t.start()
        return self
    def __exit__(self, *a):
        self._run = False
        if self._t is not None:
            self._t.join(timeout=1)

def _write_result(row):
    """Append one JSON result file to lh_bench_results/Files/bench_results.
    JSON files avoid cross-engine Delta schema conflicts."""
    import notebookutils
    result_dir = results_dir()
    notebookutils.fs.mkdirs(result_dir)
    fn = f"{row['run_id']}_{row['engine']}_{row['size']}_{row['layer']}_{row['stage']}.json"
    fn = fn.replace(":", "-").replace("/", "-")
    notebookutils.fs.put(f"{result_dir}/{fn}", json.dumps(row, default=str), True)

def run_stage(engine, size, layer, stage, fn, vcores=None):
    """Time `fn`, capture peak memory + status (success/failed/oom), persist a
    result row, and return the status string. Never raises."""
    try:
        from polars.exceptions import PanicException
        panic_types = (PanicException,)
    except ImportError:
        panic_types = ()
    start = datetime.datetime.utcnow()
    t0 = time.perf_counter(); status = "success"; err = None; rows = None
    with _PeakMem() as pm:
        try:
            rows = fn()
        except MemoryError as e:
            status, err = "oom", repr(e)
        except panic_types as e:
            status, err = "failed", repr(e)
        except Exception as e:
            m = repr(e).lower()
            status = "oom" if ("outofmemory" in m or "out of memory" in m
                               or "memoryerror" in m or "oom" in m) else "failed"
            err = repr(e)
    wall = time.perf_counter() - t0
    end = datetime.datetime.utcnow()
    # CU-seconds (Fabric: cores * 0.5 * active_seconds; startup not billed).
    # Spark counts driver + worker cores; Polars is single-node (no driver).
    driver_cores = SPARK_DRIVER_CORES if engine == "pyspark" else 0
    total_cores = (vcores + driver_cores) if vcores else None
    cu_seconds = round(total_cores * 0.5 * wall, 3) if total_cores else None
    row = {
        "run_id": RUN_ID, "engine": engine, "size": size, "layer": layer,
        "stage": stage, "status": status, "wall_seconds": round(wall, 3),
        "peak_mem_mb": round(pm.peak / 1e6, 1) if pm.peak else None,
        "rows": int(rows) if rows is not None else None,
        "error": (str(err)[:900] if err else None),
        "capacity_id": CAPACITY_ID, "vcores": vcores,
        "driver_cores": driver_cores, "total_cores": total_cores,
        "cu_seconds": cu_seconds,
        "start_utc": start.isoformat(), "end_utc": end.isoformat(),
        "recorded_utc": datetime.datetime.utcnow().isoformat(),
    }
    try:
        _write_result(row)
    except Exception as e:
        print("WARN: could not persist result:", repr(e))
    tag = "OK " if status == "success" else status.upper()
    print(f"[{tag}] {stage}: {wall:.2f}s  peak={row['peak_mem_mb']}MB  "
          f"rows={row['rows']}  cu_s={cu_seconds}")
    if err:
        print("      ->", str(err)[:300])
    return status

# %% [markdown]
# # 20 - PySpark Bronze (ingest)
# Reads TPC-DS Parquet from the **default lakehouse (`lh_bench_source`)**, adds ingest metadata, writes Delta to `lh_bench_bronze` (schema `pyspark_<size>`). Attached environment: **pyspark-bronze** (low-shuffle, NEE on).

# %%
# Parameters -- change `size` per run. Spark compute comes from the attached
# environment (pyspark-<layer>), which pins executors so worker vCores == VCORES.
engine = "pyspark"
size   = "1gb"          # one of: 1gb, 10gb, 50gb
VCORES = 16             # fair worker-vCore budget (matches Polars %%configure);
                        # enforced by the environment (executors x 8 cores).

# %%
schema_out = f"{engine}_{size}"

# %%
from pyspark.sql import functions as F

def bronze_one(name):
    def _run():
        df = (spark.read.parquet(f"Files/tpcds/{size}/{name}")   # default lakehouse = source
                .withColumn("_bench_size", F.lit(size))
                .withColumn("_bench_engine", F.lit(engine))
                .withColumn("_bronze_ingest_ts", F.current_timestamp()))
        (df.write.format("delta").mode("overwrite")
           .save(tbl("bronze", schema_out, name)))
        return None
    return _run

for t in [FACT] + DIMS:
    run_stage(engine, size, "bronze", f"bronze:{t}", bronze_one(t), vcores=VCORES)
