# Fabric benchmark notebook: 21_pyspark_silver
# Kernel: synapse_pyspark
# NOTE: generated by deploy_benchmark_notebooks.py -- edit there, not here.

# %%
# --- Shared benchmark configuration (auto-injected) ---
DATA_WS   = "f1e17fe0-3706-425e-ae65-9fda78946327"
ENG_WS    = "6dc1aae2-1e5d-4ebb-82b9-faf1a63ed5d8"
LH = {
    "source": "e219f8d3-f681-4a46-8cd0-855ab2b9e650",
    "bronze": "52711a64-ef06-4608-b3b4-1330984d3c98",
    "silver": "b7280cc4-8842-443b-b9f3-2d643ff07cf3",
    "gold":   "42643c02-ba40-4f37-ba7c-4ca0d68a3e4a",
}
RESULTS_LH  = "44150c61-a3db-4e45-9b2b-4bdfc58a00b3"
CAPACITY_ID = "ad343e36-f335-4ba3-b261-b739f7e950b0"
ONELAKE     = "onelake.dfs.fabric.microsoft.com"

def abfss(ws, item, sub):
    return f"abfss://{ws}@{ONELAKE}/{item}/{sub}"

def tbl(layer, schema, table):
    """abfss path to a Delta table in one of the data-workspace lakehouses."""
    return abfss(DATA_WS, LH[layer], f"Tables/{schema}/{table}")

def results_dir():
    return abfss(ENG_WS, RESULTS_LH, "Files/bench_results")

def onelake_opts():
    """delta-rs / object_store options for cross-workspace OneLake writes."""
    import notebookutils
    return {"bearer_token": notebookutils.credentials.getToken("storage"),
            "use_fabric_endpoint": "true"}

# TPC-DS subset used by the benchmark (one big fact + a realistic star of dims)
FACT = "store_sales"
DIMS = ["date_dim", "item", "store", "customer", "customer_address",
        "customer_demographics", "household_demographics", "promotion"]
SIZES = ["1gb", "10gb", "50gb"]

# %%
# --- Metrics harness (auto-injected): wall-clock + peak memory + OOM + CU ctx ---
import time, json, threading, datetime, os, uuid
try:
    import psutil
except Exception:
    psutil = None

def _uid():
    return datetime.datetime.utcnow().strftime("%Y%m%d%H%M%S") + "-" + uuid.uuid4().hex[:6]

RUN_ID = _uid()
print("RUN_ID =", RUN_ID)

class _PeakMem:
    """Samples process (+child) RSS in a background thread to find the peak.

    On Spark this only sees the driver; executor pressure shows up in CU and
    the Spark UI, which is why we also record capacity + time window below."""
    def __init__(self):
        self.peak = 0; self._run = False; self._t = None
    def _loop(self):
        p = psutil.Process(os.getpid()) if psutil else None
        while self._run and p is not None:
            try:
                rss = p.memory_info().rss
                for c in p.children(recursive=True):
                    try: rss += c.memory_info().rss
                    except Exception: pass
                self.peak = max(self.peak, rss)
            except Exception:
                pass
            time.sleep(0.25)
    def __enter__(self):
        if psutil is not None:
            self._run = True
            self._t = threading.Thread(target=self._loop, daemon=True); self._t.start()
        return self
    def __exit__(self, *a):
        self._run = False
        if self._t is not None:
            self._t.join(timeout=1)

def _write_result(row):
    """Append one JSON result file to lh_bench_results/Files/bench_results.
    JSON files avoid cross-engine Delta schema conflicts."""
    import notebookutils
    fn = f"{row['run_id']}_{row['engine']}_{row['size']}_{row['layer']}_{row['stage']}.json"
    fn = fn.replace(":", "-").replace("/", "-")
    notebookutils.fs.put(f"{results_dir()}/{fn}", json.dumps(row, default=str), True)

def run_stage(engine, size, layer, stage, fn, vcores=None):
    """Time `fn`, capture peak memory + status (success/failed/oom), persist a
    result row, and return the status string. Never raises."""
    start = datetime.datetime.utcnow()
    t0 = time.perf_counter(); status = "success"; err = None; rows = None
    with _PeakMem() as pm:
        try:
            rows = fn()
        except MemoryError as e:
            status, err = "oom", repr(e)
        except Exception as e:
            m = repr(e).lower()
            status = "oom" if ("outofmemory" in m or "out of memory" in m
                               or "memoryerror" in m or "oom" in m) else "failed"
            err = repr(e)
    wall = time.perf_counter() - t0
    end = datetime.datetime.utcnow()
    row = {
        "run_id": RUN_ID, "engine": engine, "size": size, "layer": layer,
        "stage": stage, "status": status, "wall_seconds": round(wall, 3),
        "peak_mem_mb": round(pm.peak / 1e6, 1) if pm.peak else None,
        "rows": int(rows) if rows is not None else None,
        "error": (str(err)[:900] if err else None),
        "capacity_id": CAPACITY_ID, "vcores": vcores,
        "start_utc": start.isoformat(), "end_utc": end.isoformat(),
        "recorded_utc": datetime.datetime.utcnow().isoformat(),
    }
    try:
        _write_result(row)
    except Exception as e:
        print("WARN: could not persist result:", repr(e))
    tag = "OK " if status == "success" else status.upper()
    print(f"[{tag}] {stage}: {wall:.2f}s  peak={row['peak_mem_mb']}MB  rows={row['rows']}")
    if err:
        print("      ->", str(err)[:300])
    return status

# %% [markdown]
# # 21 - PySpark Silver (clean / join / dedupe)
# Joins the fact to its dimensions from **`lh_bench_bronze`** (default lakehouse), dedupes on the natural key, writes `silver.sales_conformed`. Attached environment: **pyspark-silver** (AQE + skew join, higher shuffle partitions).

# %%
# Parameters -- change `size` per run. Spark compute comes from the attached
# environment (pyspark-<layer>); no need to set vCores manually.
engine = "pyspark"
size   = "1gb"          # one of: 1gb, 10gb, 50gb

# %%
schema_out = f"{engine}_{size}"

# %%
from pyspark.sql import functions as F, Window

def read_b(t):
    return spark.read.format("delta").load(tbl("bronze", schema_out, t))

def silver_conform():
    ss = read_b("store_sales")
    dd = read_b("date_dim").select("d_date_sk", "d_year", "d_moy", "d_date")
    it = read_b("item").select("i_item_sk", "i_category", "i_brand", "i_current_price")
    st = read_b("store").select("s_store_sk", "s_store_name", "s_state")
    cu = read_b("customer").select("c_customer_sk", "c_current_addr_sk", "c_birth_year")
    ca = read_b("customer_address").select("ca_address_sk", "ca_state", "ca_city")
    df = (ss.join(dd, ss.ss_sold_date_sk == dd.d_date_sk, "inner")
            .join(it, ss.ss_item_sk == it.i_item_sk, "inner")
            .join(st, ss.ss_store_sk == st.s_store_sk, "left")
            .join(cu, ss.ss_customer_sk == cu.c_customer_sk, "left")
            .join(ca, F.col("c_current_addr_sk") == ca.ca_address_sk, "left"))
    w = Window.partitionBy("ss_ticket_number", "ss_item_sk").orderBy(F.lit(1))
    df = (df.withColumn("_rn", F.row_number().over(w)).filter(F.col("_rn") == 1).drop("_rn")
            .withColumn("gross_amount", F.col("ss_sales_price") * F.col("ss_quantity"))
            .withColumn("net_amount", F.col("ss_net_paid")))
    (df.write.format("delta").mode("overwrite")
       .save(tbl("silver", schema_out, "sales_conformed")))
    return None

run_stage(engine, size, "silver", "silver:conform", silver_conform)
