// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table adf_diag_logs_tbl (EventProcessedUtcTime:datetime, PartitionId:long, EventEnqueuedUtcTime:datetime, ArrayIndex_records:long, ArrayValue_records:dynamic) 
.create-merge table adf_schema_17tu0x2 (records:dynamic, EventProcessedUtcTime:datetime, PartitionId:long, EventEnqueuedUtcTime:datetime) 
.create-merge table adf_schema_1u9io2p (records:dynamic, EventProcessedUtcTime:datetime, PartitionId:long, EventEnqueuedUtcTime:datetime) 
.create-merge table adf_schema_gb97e9 (records:dynamic, EventProcessedUtcTime:datetime, PartitionId:long, EventEnqueuedUtcTime:datetime) 
.create-merge table adf_schema_104fvyz (records:dynamic, EventProcessedUtcTime:datetime, PartitionId:long, EventEnqueuedUtcTime:datetime) 
.create-merge table adf_schema_z16wac (records:dynamic, EventProcessedUtcTime:datetime, PartitionId:long, EventEnqueuedUtcTime:datetime) 
.create-merge table adf_schema_1t42bd8 (records:dynamic, EventProcessedUtcTime:datetime, PartitionId:long, EventEnqueuedUtcTime:datetime) 
.create-merge table adf_schema_7rl9yh (records:dynamic, EventProcessedUtcTime:datetime, PartitionId:long, EventEnqueuedUtcTime:datetime) 
.create-merge table adf_schema_1ltnscp (records:dynamic, EventProcessedUtcTime:datetime, PartitionId:long, EventEnqueuedUtcTime:datetime) 
.create-merge table adf_schema_od5vx (records:dynamic, EventProcessedUtcTime:datetime, PartitionId:long, EventEnqueuedUtcTime:datetime) 
